POST http://localhost:3000/user/signup
Content-Type: application/json

{
  "username": "jeff",
  "email": "jeff@gmail.com",
  "password": "bestPasswor"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "tommy@gmail.com",
  "password": "password1234"
}