name: CI Pipeline

on: 
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main  # Runs on PR to main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetch the code

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use Node.js 18

      - name: Install Dependencies
        run: npm install  # Install project dependencies

      - name: Run Linter
        run: npm run lint  # Run ESLint or any linter you use

      - name: Run Tests
        run: npm test --passWithNoTests # Run tests

      - name: Check Test Coverage
        run: npm run test -- --coverage  # Generate test coverage report
