name: Test Project

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4
        with: 
          node-version: 20
      - run: npm ci
      - run: npm start &
      - run: sleep 5
      - run: npm test
      - run: pkill -f "node"
      
